"""URL-only feature extraction.

Every feature here is computed from the URL string alone (no network calls),
so the exact same code is used for training (Colab) and prediction (Streamlit).
Do NOT edit this file after training without retraining the model.
"""
import math
import re
from collections import Counter
from urllib.parse import urlparse

SHORTENERS = {
    "bit.ly", "goo.gl", "t.co", "tinyurl.com", "ow.ly", "is.gd", "buff.ly",
    "adf.ly", "bit.do", "cutt.ly", "rb.gy", "shorturl.at", "tiny.cc",
}
PHISH_HINTS = ["wp", "login", "includes", "admin", "content", "site", "images",
               "js", "alibaba", "css", "myaccount", "dropbox", "themes",
               "plugins", "signin", "view"]
SENSITIVE_WORDS = ["secure", "account", "update", "verify", "confirm", "banking",
                   "password", "paypal", "ebay", "apple", "microsoft", "amazon",
                   "support", "webscr", "billing", "wallet", "security"]
SUSPICIOUS_TLDS = {"zip", "country", "kim", "science", "work", "party", "gq",
                   "link", "click", "top", "xyz", "tk", "ml", "ga", "cf", "cn",
                   "men", "loan", "download", "review", "stream", "icu"}


def _words(s):
    return [w for w in re.split(r"[\W_]+", s) if w]


def _stats(words):
    if not words:
        return 0, 0, 0.0
    lens = [len(w) for w in words]
    return min(lens), max(lens), sum(lens) / len(lens)


def _entropy(s):
    if not s:
        return 0.0
    n = len(s)
    return -sum(c / n * math.log2(c / n) for c in Counter(s).values())


def _max_repeat(s):
    best = run = 1 if s else 0
    for a, b in zip(s, s[1:]):
        run = run + 1 if a == b else 1
        best = max(best, run)
    return best


def _parse(url):
    try:
        p = urlparse(url if "//" in url else "http://" + url)
        host = (p.hostname or "").lower()
        try:
            port = p.port
        except ValueError:
            port = None
        return p.scheme, host, p.path or "", p.query or "", port
    except ValueError:
        return "http", "", "", "", None


def extract_url_features(url: str) -> dict:
    url = str(url).strip()
    low = url.lower()
    scheme, host, path, query, port = _parse(url)
    parts = host.split(".") if host else []
    tld = parts[-1] if parts else ""
    subdomains = parts[:-2] if len(parts) > 2 else []

    host_words, path_words, raw_words = _words(host), _words(path), _words(url)
    h_min, h_max, h_avg = _stats(host_words)
    p_min, p_max, p_avg = _stats(path_words)
    r_min, r_max, r_avg = _stats(raw_words)
    n_digits_url = sum(c.isdigit() for c in url)
    n_digits_host = sum(c.isdigit() for c in host)

    f = {
        "length_url": len(url),
        "length_hostname": len(host),
        "length_path": len(path),
        "length_query": len(query),
        "ip": int(bool(re.fullmatch(r"(\d{1,3}\.){3}\d{1,3}", host))),
        "nb_dots": url.count("."),
        "nb_hyphens": url.count("-"),
        "nb_at": url.count("@"),
        "nb_qm": url.count("?"),
        "nb_and": url.count("&"),
        "nb_eq": url.count("="),
        "nb_underscore": url.count("_"),
        "nb_tilde": url.count("~"),
        "nb_percent": url.count("%"),
        "nb_slash": url.count("/"),
        "nb_star": url.count("*"),
        "nb_colon": url.count(":"),
        "nb_comma": url.count(","),
        "nb_semicolumn": url.count(";"),
        "nb_dollar": url.count("$"),
        "nb_space": url.count(" ") + url.count("%20"),
        "nb_www": low.count("www"),
        "nb_com": low.count(".com"),
        "nb_dslash": url.count("//"),
        "http_in_path": int("http" in path.lower()),
        "https_token": int(scheme == "https"),
        "nb_digits_url": n_digits_url,
        "ratio_digits_url": n_digits_url / len(url) if url else 0,
        "ratio_digits_host": n_digits_host / len(host) if host else 0,
        "entropy_url": _entropy(url),
        "entropy_host": _entropy(host),
        "punycode": int("xn--" in host),
        "port": int(port is not None),
        "tld_in_path": int(bool(tld) and tld in path.lower()),
        "tld_in_subdomain": int(bool(tld) and tld in subdomains),
        "abnormal_subdomain": int(bool(re.match(r"^w{2,3}\d+\.", host))),
        "nb_subdomains": len(subdomains),
        "prefix_suffix": int("-" in host),
        "shortening_service": int(host in SHORTENERS),
        "path_extension": int(bool(re.search(r"\.(txt|exe|js|php|html?)$", path.lower()))),
        "length_words_raw": len(raw_words),
        "char_repeat": _max_repeat(url),
        "shortest_words_raw": r_min,
        "shortest_word_host": h_min,
        "shortest_word_path": p_min,
        "longest_words_raw": r_max,
        "longest_word_host": h_max,
        "longest_word_path": p_max,
        "avg_words_raw": r_avg,
        "avg_word_host": h_avg,
        "avg_word_path": p_avg,
        "phish_hints": sum(low.count(h) for h in PHISH_HINTS),
        "sensitive_words": sum(low.count(w) for w in SENSITIVE_WORDS),
        "suspecious_tld": int(tld in SUSPICIOUS_TLDS),
        "tld_length": len(tld),
    }
    return {k: float(v) for k, v in f.items()}


FEATURE_NAMES = list(extract_url_features("http://example.com").keys())
